name: Build RPM Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-rpm:
    runs-on: ubuntu-latest
    container: 
      image: fedora:39
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          dnf clean all
          dnf -y update
          dnf install -y \
            curl \
            git \
            cmake \
            ninja-build \
            clang \
            pkg-config \
            gtk3-devel \
            rpm-build \
            xz \
            wget \
            unzip \
            which \
            mesa-libGLU \
            findutils

      - name: Setup Flutter
        run: |
          git config --global --add safe.directory '*'
          git config --global --add safe.directory $GITHUB_WORKSPACE
          
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.16.9-stable.tar.xz
          tar xf flutter_linux_3.16.9-stable.tar.xz
          
          export PATH="$PATH:$PWD/flutter/bin"
          flutter config --no-analytics
          flutter config --enable-linux-desktop
          flutter doctor -v

      - name: Build Application
        run: |
          export PATH="$PATH:$PWD/flutter/bin"
          flutter pub get
          flutter build linux --release

      - name: Create RPM Package
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | cut -d' ' -f2)
          
          # Setup RPM build environment
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          
          # Create source tarball
          cd build/linux/x64/release/bundle
          tar czf ~/rpmbuild/SOURCES/wine-launcher-$VERSION.tar.gz *
          cd -
          
          # Copy assets
          cp assets/wine-launcher.desktop ~/rpmbuild/SOURCES/
          cp assets/wine-launcher.png ~/rpmbuild/SOURCES/
          
          # Create spec file
          cat > ~/rpmbuild/SPECS/wine-launcher.spec << EOF
          Name:           wine-launcher
          Version:        $VERSION
          Release:        1%{?dist}
          Summary:        A Wine and Proton prefix manager for Linux
          
          License:        MIT
          URL:            https://github.com/yourusername/wine-launcher
          BuildArch:      x86_64
          
          Source0:        %{name}-%{version}.tar.gz
          Source1:        %{name}.desktop
          Source2:        %{name}.png
          
          Requires:       wine
          Requires:       winetricks
          Requires:       gtk3
          
          %description
          A Flutter-based game launcher for Wine and Proton with support for managing
          multiple Wine prefixes and game configurations.
          
          %prep
          %setup -q -c
          
          %install
          mkdir -p %{buildroot}%{_bindir}
          mkdir -p %{buildroot}%{_libdir}/%{name}
          mkdir -p %{buildroot}%{_datadir}/applications
          mkdir -p %{buildroot}%{_datadir}/icons/hicolor/128x128/apps
          
          cp -r * %{buildroot}%{_libdir}/%{name}/
          
          echo '#!/bin/bash' > %{buildroot}%{_bindir}/%{name}
          echo 'exec %{_libdir}/%{name}/wine-launcher "\$@"' >> %{buildroot}%{_bindir}/%{name}
          chmod 755 %{buildroot}%{_bindir}/%{name}
          
          install -D -m 644 %{SOURCE1} %{buildroot}%{_datadir}/applications/%{name}.desktop
          install -D -m 644 %{SOURCE2} %{buildroot}%{_datadir}/icons/hicolor/128x128/apps/%{name}.png
          
          %files
          %{_bindir}/%{name}
          %{_libdir}/%{name}
          %{_datadir}/applications/%{name}.desktop
          %{_datadir}/icons/hicolor/128x128/apps/%{name}.png
          
          %changelog
          * $(date '+%a %b %d %Y') Builder <builder@localhost> - %{version}-%{release}
          - Initial package release
          EOF
          
          # Build RPM
          rpmbuild -bb ~/rpmbuild/SPECS/wine-launcher.spec

      - name: Upload RPM
        uses: actions/upload-artifact@v4
        with:
          name: wine-launcher-rpm
          path: ~/rpmbuild/RPMS/x86_64/wine-launcher-*.rpm

  create-release:
    needs: build-rpm
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    
    steps:
      - name: Download RPM artifact
        uses: actions/download-artifact@v4
        with:
          name: wine-launcher-rpm
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: wine-launcher-*.rpm
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 